### ISSUE TITLE
FacebookOAuthResult null

### ISSUE THREAD

**Issue by smohiuddin** [prabirshrestha/FB-CSharp-SDK-First-FB-Application#1]
Hi - 
I am exactly replicating the sample that you have provided here with my own app id. I am able to get the permissions page and accept the permissions and get the "Success page" but FacebookOAuthResult is still null. Do you have any idea why is this the case? Does this have to do with the new SDK?

**Comment by prabirshrestha** [comment]
i tried running the sample and it works fine. could you paste your code on how you are doing it.

**Comment by smohiuddin** [comment]
First of All - Thank you for your help. The code is below.

In FacebookLoginDialog.xaml.cs I have

```
public partial class FacebookLoginDialog : Window
{
    private Uri navigateUrl;

    public FacebookOAuthResult FacebookOAuthResult { get; private set; }

    public FacebookLoginDialog(string appId, string[] extendedPermissions, bool logout)
    {
        var oauth = new FacebookOAuthClient { AppId = appId };

        var loginParameters = new Dictionary<string, object>
                                  {
                                      { "response_type", "token" },
                                      { "display", "popup" }
                                  };

        if (extendedPermissions != null && extendedPermissions.Length > 0)      {
            var scope = new StringBuilder();
            scope.Append(string.Join(",", extendedPermissions));
            loginParameters["scope"] = scope.ToString();
        }

        var loginUrl = oauth.GetLoginUrl(loginParameters);

        this.navigateUrl = loginUrl;

        InitializeComponent();
    }

    public FacebookLoginDialog(string appId, string[] extendedPermissions)
        : this(appId, extendedPermissions, false)
    {
    }

    private void webBrowser_Navigated(object sender, System.Windows.Navigation.NavigationEventArgs e)
    {
        FacebookOAuthResult oauthResult;
        if (FacebookOAuthResult.TryParse(e.Uri, out oauthResult))
        {
            this.FacebookOAuthResult = oauthResult;
            this.DialogResult = oauthResult.IsSuccess;
        }
        else
        {
            Console.WriteLine("OATH NULL");
            this.FacebookOAuthResult = null;
        }
    }

    private void Window_Loaded(object sender, RoutedEventArgs e)
    {
        webBrowser.Navigate(navigateUrl.AbsoluteUri);
    }
```

In the MainWindow.xaml.cs I have 

 public partial class MainWindow : Window    {
        private string appId = "APP ID HERE";
        private string[] extendedPermissions = new[] {"user_about_me", "offline_access", "publish_stream"};

```
    public MainWindow()      {
        InitializeComponent();
    }

    private void FacebookLoginButtonClicked(object sender, RoutedEventArgs e)    {
        var facebookLoginDialog = new FacebookLoginDialog(appId, extendedPermissions);
        facebookLoginDialog.ShowDialog();

        DisplayAppropriateMessage(facebookLoginDialog.FacebookOAuthResult);
    }

    private void DisplayAppropriateMessage(FacebookOAuthResult facebookOAuthResult)     {

        var fb = new FacebookClient(facebookOAuthResult.AccessToken);


        if (facebookOAuthResult == null)     {
            Console.WriteLine("Complain");
            return;
        }

        if (facebookOAuthResult.IsSuccess)  {
            dynamic result = fb.Get("/me");
            MessageBox.Show("Hi " + result.name);
        }
        else  {
            MessageBox.Show(facebookOAuthResult.ErrorDescription);
        }
    }

}
```

**Comment by prabirshrestha** [comment]
what about the sample in the repository, is that code working for you?

if that is not working you might be having problems with your facebook app settings. 
Make sure your Application Type is set to "HTML5 / mobile web" and not "native app"

**Comment by smohiuddin** [comment]
The Sample in the Repository is working for me. That Facebook app setting wasn't right so I did change it to "HTML5 / mobile web". I am creating a WPF application unlike your Sample Code which uses forms. Could there be an issue with that because I've been struggling with this problem for about a week now and can't figure it out.
Thanks for your help.

**Comment by prabirshrestha** [comment]
download the Facebook C# SDK source code, there is a folder called samples which contains WPF sample, you might want to check that inorder to get started wpf.

**Comment by smohiuddin** [comment]
Yes  - thanks for the tip but that sample does not bring up any permissions page. It just brings up the regular facebook page.

**Comment by mudnug** [comment]
I also have application users telling me they are only seeing the Success page after login. I have tracked this down a little further and verified, in my case, that facebook is sending the access_token, but the Fragment property of the Uri is "" so FacebookOAuthResult.TryParse returns false and provides a null FacebookOAuthResult.

I am wondering if something changed with IE9.

To be sure, I have run CSWPFSimpleApp after changing only the AppId.

Perhaps this will help speed the resolution.

**Comment by mudnug** [comment]
I am now using the workaround described at http://social.msdn.microsoft.com/Forums/en/wpf/thread/ffdf22f8-0df4-4ce4-bdee-632e4cbb5fbb

**Comment by prabirshrestha** [comment]
great. at least you found a solution.
for now i'm closing this issue.
